"use client";

import { WalletCheckResponse, formatUSDFull, truncateAddress, RiskLevel, RISK_CONFIG } from "@/lib/metacomp";
import { scoreReportConfidence, vendorAlertCoverage } from "@/lib/confidence";
import { FileText, Calendar, Shield, Gauge } from "lucide-react";
import { cn } from "@/lib/utils";

interface ComplianceReportProps {
  data: WalletCheckResponse["data"];
}

const BAND_STYLES: Record<string, string> = {
  CLEAR: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
  PARTIAL: "bg-amber-500/10 border-amber-500/20 text-amber-400",
  LOW: "bg-red-500/10 border-red-500/20 text-red-400",
};

export function ComplianceReport({ data }: ComplianceReportProps) {
  const config = RISK_CONFIG[data.level];
  const confidence = scoreReportConfidence({
    level: data.level,
    vendorAlertCoverage: vendorAlertCoverage([data.extra.chainalysis, data.extra.vendor1, data.extra.vendor2, data.extra.vendor3]),
    hasFlowBreakdown: Boolean(data.extra.incomingRiskExposureBreakdown && data.extra.outgoingRiskExposureBreakdown),
    transactionSampleSize: data.extra.tx.length,
    timeCoveragePresent: Boolean(data.extra.earliestTransactionTime && data.extra.latestTransactionTime),
  });

  return (
    <div className="bg-slate-800/50 border border-slate-700/50 rounded-xl p-5">
      <div className="flex items-center gap-2 mb-4">
        <FileText className="h-4 w-4 text-slate-400" />
        <h3 className="text-sm font-semibold text-slate-300">Compliance Report</h3>
      </div>

      <div className="space-y-3 text-xs">
        <Row label="Wallet Address" value={truncateAddress(data.address, 10)} mono />
        <Row label="Network" value={data.network} />
        <Row label="Risk Level">
          <span className={cn("font-bold", config.text)}>{data.level}</span>
        </Row>
        <Row label="Screening Date" value={new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} />
        <Separator />
        <Row label="Total Incoming" value={formatUSDFull(data.extra.totalIncoming)} mono />
        <Row label="Total Outgoing" value={formatUSDFull(data.extra.totalOutgoing)} mono />
        <Row label="Wallet Balance" value={formatUSDFull(data.extra.walletBalance)} mono />
        <Separator />
        <Row label="High-Risk Categories" value={data.extra.highRiskCategories.length.toString()} />
        {data.extra.highRiskCategories.length > 0 && (
          <div className="flex flex-wrap gap-1.5 ml-24 mt-1">
            {data.extra.highRiskCategories.map((cat, idx) => (
              <span
                key={idx}
                className="px-2 py-0.5 rounded-full text-[10px] bg-red-500/10 border border-red-500/20 text-red-400"
              >
                {cat}
              </span>
            ))}
          </div>
        )}
        <Separator />
        <Row label="Incoming High-Risk" value={formatUSDFull(data.extra.incomingRiskExposureBreakdown.highRiskAmount)} mono />
        <Row label="Outgoing High-Risk" value={formatUSDFull(data.extra.outgoingRiskExposureBreakdown.highRiskAmount)} mono />
      </div>

      <Separator />
      <div className="mt-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Gauge className="h-3.5 w-3.5 text-slate-400" />
            <span className="text-[11px] font-semibold text-slate-300">Report Confidence</span>
          </div>
          <span className={cn("px-2 py-0.5 rounded-full text-[10px] border", BAND_STYLES[confidence.band])}>
            {confidence.band} · {confidence.score}/100
          </span>
        </div>
        <div className="mt-2 space-y-1">
          {confidence.factors.map((factor) => (
            <div key={factor.name} className="flex items-center justify-between gap-2 text-[10px]">
              <span className="text-slate-500">{factor.name}</span>
              <span className="text-slate-600">{factor.evidence}</span>
              <span className="font-mono text-slate-400">{factor.points}/{factor.cap}</span>
            </div>
          ))}
        </div>
        <p className="mt-2 text-[9px] text-slate-600">
          Deterministic capped-factor score over report completeness — evidence carried verbatim above.
        </p>
      </div>

      <div className="mt-4 pt-4 border-t border-slate-700/30 flex items-center gap-2 text-[10px] text-slate-600">
        <Shield className="h-3 w-3" />
        Generated by MetaComp Vision X — Multi-Vendor AML Screening
      </div>
    </div>
  );
}

function Row({
  label,
  value,
  mono,
  children,
}: {
  label: string;
  value?: string;
  mono?: boolean;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-start gap-3">
      <span className="text-slate-500 w-36 shrink-0">{label}</span>
      {children || (
        <span className={cn("text-slate-300", mono && "font-mono")}>{value}</span>
      )}
    </div>
  );
}

function Separator() {
  return <div className="border-t border-slate-700/20 my-2" />;
}
